require 'gosu'
require 'rmagick'
require_relative 'lib/settings'
require_relative 'lib/elements/court'
require_relative 'lib/elements/ball'
require_relative 'lib/elements/paddle'
require_relative 'lib/pingpong_window'
